export const MENU_SCENARIO = {
    MAIN_SCENE: "MAIN_SCENE",
};

export const SETTINGS_SCENARIO = {
    MAIN_SCENE: "SETTINGS_MAIN_SCENE",
    PLATOON_TYPE_SCENE: "SETTINGS_PLATOON_TYPE_SCENE",
    PLATOON_SCENE: "SETTINGS_PLATOON_SCENE",
};

export const SCHEDULE_SCENARIO = {
    PLATOON_SCENE: "SCHEDULE_PLATOON_SCENE",
    PLATOON_TYPE_SCENE: "SCHEDULE_PLATOON_TYPE_SCENE",
    DATE_SCENE: "SCHEDULE_DATE_SCENE",
};

export const DEFAULT_SCHEDULE_SCENARIO = {
    DATE_SCENE: "DEFAULT_SCHEDULE_DATE_SCENE",
};

export const NEWS_SCENARIO = {
    NEWS_SCENE: "NEWS_SCENE",
};
